from rsf.proj import *

parametersCube = 'parametersCube'
stackedSection = 'stackedSection'
dataCube = 'dataCube'

Flow(dataCube,'interpolatedDataCube','window f1=250 n1=251 f3=120 n3=242 n2=30 f2=0')
Flow('rnip',parametersCube,'window n3=1 f3=1')
Flow('beta',parametersCube,'window n3=1 f3=2')

v0=1.5

Flow('vnmo',[stackedSection,'rnip','beta'],
	'''
	math rnip=${SOURCES[1]} beta=${SOURCES[2]} output="sqrt((2*%g*rnip)/(x1*cos(beta)*cos(beta)))"
	''' % (v0))
# NMO and stack
Flow('nmo',[dataCube,'vnmo'],'nmo half=n velocity=${SOURCES[1]}')

Flow('nmoStack','nmo','stack')

