from rsf.proj import *

sv='sv_2'

Flow('sv_2.asc',None,
        '''
        echo 1.508 1.508 1.508 1.508 1.69 1.69 1.69 1.69 1.69 2.0 2.0 2.0 2.0 n1=13 d1=0.25 o1=0. data_format=ascii_float in=${TARGETS[0]}
        ''')

# Layer's velocity
Flow(sv,'sv_2.asc',
        '''
        dd type=float form=native |
        spray axis=2 n=9 d=0.5 o=1.
        ''')

Flow('vel',sv,'./model1d.x')
